import "../styles/globals.scss";

import type { AppProps } from "next/app";
import Layout from "../components/layouts/Layout";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "../utils/apollo-client";
import Head from "next/head";
import { LayoutContextProvider } from "../utils/context/LayoutContext";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <LayoutContextProvider>
      <ApolloProvider client={apolloClient}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pokemon-icon.png" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ApolloProvider>
    </LayoutContextProvider>
  );
}

export default MyApp;
