import "../styles/globals.scss";

import type { AppProps } from "next/app";
import Layout from "../components/layouts/Layout";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "../utils/apollo-client";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ApolloProvider client={apolloClient}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokemon-icon.png" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ApolloProvider>
  );
}

export default MyApp;
