query getPokemonByName($name: String!) {
  pokemonByName(name: $name) {
    id
    name
    maxCP
    maxHP
    height {
      minimum
      maximum
    }
    weight {
      minimum
      maximum
    }
    sound
    image
    types
    isFavorite
    evolutions {
      id
      name
      image
      isFavorite
    }
  }
}
